package com.example.parkingapp.util

object Constance {

    const val PREF_TABLE_NAME = "PREF_TABLE_NAME"
    const val PREF_EMAIL_NAME = "PREF_EMAIL_NAME"

    const val NOTIFICATION_CHANNEL_ID1 = "NOTIFICATION_CHANNEL_ID1"

    const val NOTIFICATION_CHANNEL_ID2 = "NOTIFICATION_CHANNEL_ID2"

    const val NOTIFICATION_ID1 = 1

    const val NOTIFICATION_ID2 = 2

    const val ACTION_SHOW_PARKING_FRAGMENT = "ACTION_SHOW_PARKING_FRAGMENT"

    const val MILLIS_TO_SERVICE = "MILLIS_TO_SERVICE"

    const val NUMBER_TO_SERVICE = "NUMBER_TO_SERVICE"

    const val PENDING_INTENT_NUMBER = "PENDING_INTENT_NUMBER"

}